### ISSUE TITLE
Support Django 4.0

### ISSUE THREAD

**Issue by TimurKady** [s-block/django-nested-inline#135]
Features removed in 4.0: django.utils.encoding.force_text() are removed (admin.py, line 13)

**Comment by OskarPersson** [comment]
Add PR and I'll look into it :)

**Comment by Thorbenl** [comment]
@OskarPersson @TimurKhan  I made a PR for this :) #138

**Comment by Thorbenl** [comment]
@OskarPersson Thanks! We can soon upgrade it at work then
