### ISSUE TITLE
New PyPi Release

### ISSUE THREAD

**Issue by daniel-brenot** [s-block/django-nested-inline#140]
Would this be able to be released to PyPi at some point soon? We currently have to point our requirements file at a git commit in order to have the support for CSRF and it is not ideal.

Appreciate the work, thanks!

**Comment by Thorbenl** [comment]
I second this, a new release would be nice, adding the Django support as well.

**Comment by s-block** [comment]
Would either of you like to re-release this? I can add you as a contributor and add you on pypi. I don't really get time to update this anymore.

**Comment by Thorbenl** [comment]
@daniel-brenot Do you have any experience in this? I never released something in python, but i assume I could look up a guide and release this version.

@s-block feel free to add me, and I see what I can do.

**Comment by daniel-brenot** [comment]
Yes I do. Feel free to add me if you would like.

**Comment by s-block** [comment]
@daniel-brenot I have sent you an email. I have added you as a collaborator to this repo and just need your pypi user so I can add you to that asa well.

**Comment by daniel-brenot** [comment]
> @daniel-brenot I have sent you an email. I have added you as a collaborator to this repo and just need your pypi user so I can add you to that asa well.

My username on pypi is daniel.brenot

**Comment by s-block** [comment]
@daniel-brenot I have added you to pypi

**Comment by Thorbenl** [comment]
@daniel-brenot did u make a release?

```Could not find a version that satisfies the requirement django-nested-inline==0.4.5 (from versions: 0.2, 0.2.1, 0.2.2, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4)
ERROR: No matching distribution found for django-nested-inline==0.4.5
```

**Comment by daniel-brenot** [comment]
I did now. Sorry for the delay
