### ISSUE TITLE
Django 4.0+ deprecated django.utils.encoding.force_text

### ISSUE THREAD

**Issue by jnegro** [s-block/django-nested-inline#141]
The following error occurs with Django 4.0+ because force_text has been changed to force_str:

`File "/usr/local/lib/python3.9/site-packages/nested_inline/admin.py", line 13, in <module>
from django.utils.encoding import force_text
ImportError: cannot import name 'force_text' from 'django.utils.encoding' (/usr/local/lib/python3.9/site-packages/django/utils/encoding.py)`

The issue is documented there:
https://docs.djangoproject.com/en/4.0/ref/utils/#module-django.utils.encoding

According to this articicle we need to change to 'force_str'

**Comment by Thorbenl** [comment]
@jnegro It is fixed in and in master, we are just awaiting a release of `0.4.5`

You can use `git+https://github.com/s-block/django-nested-inline.git@617f5aa8ce940688f702e0b32a30816473c54ab4´ in your `requirements` file for the time being.

**Comment by jnegro** [comment]
Thanks for the quick response.  Sorry I did not see it within that ticket!

**Comment by daniel-brenot** [comment]
Just made a release to pypi. You can now download version 0.4.5

**Comment by jnegro** [comment]
Thank you for the update!
