### ISSUE TITLE
0.3.5 on PyPI?

### ISSUE THREAD

**Issue by rsenk330** [s-block/django-nested-inline#33]
Could you please publish 0.3.5 on PyPI?

**Comment by sky-chen** [comment]
before that: `pip install git+https://github.com/s-block/django-nested-inline.git`

**Comment by rsenk330** [comment]
While that does work, we try to avoid doing that because it increases the time it takes for our production deploys.

**Comment by gfairchild** [comment]
I totally agree. 0.3.5 contains some really important fixes and needs to hit PyPI ASAP.

**Comment by Depado** [comment]
Any news on that ? :)

**Comment by stretch4x4** [comment]
We could also really use this being updated on PyPI

**Comment by paxelito** [comment]
Any news?

**Comment by gfairchild** [comment]
I'd love to see MR #35 incorporated first, but yes, this really needs to be updated on PyPI.

@s-block, would it help you to define extra roles on PyPI? That way, other people can help keep the package up to date.

**Comment by kwilcox** [comment]
:+1: poke poke poke poke

**Comment by s-block** [comment]
0.3.5 now on Pypi

**Comment by gfairchild** [comment]
Fantastic! Thank you!

**Comment by stretch4x4** [comment]
Cheers @s-block that is awesome

**Comment by PetrDlouhy** [comment]
This issue seems to be solved and should be closed. I added new issue #74 for Django 1.10 compatible package though.

**Comment by s-block** [comment]
done
